// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) {{LICENSE_YEAR}}, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerina/oauth2;
import ballerina/test;

// configurable string hubspotClientId = ?;
// configurable string hubspotClientSecret = ?;
// configurable string hubspotRefreshToken = 

final string clientId = "ee37df47-6d02-4e26-bab9-1c259ad98d25";
final string clientSecret = "7287c09b-0e28-46cc-b535-626ff594f212";
final string refreshToken = "na2-f206-59d7-41fb-9dae-60bc226e956b";

final boolean isLiveServer = true;
final string serviceUrl = isLiveServer ? "https://api.hubapi.com/crm/v3/objects/communications" : "http://localhost:9090";

final Client hecClient = check initClient();

isolated function initClient() returns Client|error {
    if isLiveServer {
        OAuth2RefreshTokenGrantConfig auth = {
            clientId,
            clientSecret,
            refreshToken,
            credentialBearer: oauth2:POST_BODY_BEARER
        };
        return check new ({auth}, serviceUrl);
    }

    return check new ({
        auth: {
            token: "test-token"
        }
    }, serviceUrl);
}

isolated string testCommunicationId = "";
isolated string[] testBatchIds = [];

final string testAssociateId1 = "83849040631";
final string testAssociateId2 = "83849299661";
final int contactAssociationTypeId = 81;
final string testOwnerId = "77366318";

@test:Config {
    groups: ["live_test", "mock_tests"]
}
isolated function testCreateMessage() returns error? {
    SimplePublicObject|error response = hecClient->/.post(
        payload = {
            properties: {
                "hs_communication_channel_type": "SMS",
                "hs_communication_logged_from": "CRM",
                "hs_communication_body": "Texted Linda to confirm that we're ready to move forward with the contract.",
                "hs_timestamp": "2022-11-12T15:48:22Z",
                "hubspot_owner_id": testOwnerId
            },
            associations: [
                {
                    types: [
                        {
                            associationCategory: "HUBSPOT_DEFINED",
                            associationTypeId: 81
                        }
                    ],
                    to: {
                        id: testAssociateId1
                    }
                },
                {
                    types: [
                        {
                            associationCategory: "HUBSPOT_DEFINED",
                            associationTypeId: 81
                        }
                    ],
                    to: {
                        id: testAssociateId2
                    }
                }
            ]
        }
    );

    test:assertEquals(response is SimplePublicObject, true, "Response is not an instance of SimplePublicObject");

    if (response is SimplePublicObject) {
        lock {
            testCommunicationId = response.id;
        }
    }
}

@test:Config {
    dependsOn: [testCreateMessage],
    groups: ["live_test", "mock_tests"]
}
isolated function testGetMessages() returns error? {

    CollectionResponseSimplePublicObjectWithAssociationsForwardPaging|error response = hecClient->/.get();

    test:assertEquals(response is CollectionResponseSimplePublicObjectWithAssociationsForwardPaging, true, "Response is not an array of BatchResponseSimplePublicObject");
}

@test:Config {
    dependsOn: [testCreateMessage],
    groups: ["live_test", "mock_tests"]
}
isolated function testGetMessageById() returns error? {

    string testId = "";

    lock {
        testId = testCommunicationId;
    }

    SimplePublicObjectWithAssociations|error response = hecClient->/[testId].get();

    test:assertEquals(response is SimplePublicObjectWithAssociations, true, "Response is not an instance of SimplePublicObjectWithAssociations");
}

@test:Config {
    dependsOn: [testCreateMessage],
    groups: ["live_test", "mock_tests"]
}
isolated function testUpdateMessage() returns error? {
    string testId = "";

    lock {
        testId = testCommunicationId;
    }

    SimplePublicObject|error response = hecClient->/[testId].patch(
        payload = {
            properties: {
                "hs_communication_channel_type": "SMS",
                "hs_communication_logged_from": "CRM",
                "hs_communication_body": "Texted Linda to confirm that we're ready to move forward with the contract.",
                "hs_timestamp": "2022-11-12T15:48:22Z",
                "hubspot_owner_id": testOwnerId
            }
        }
    );

    test:assertEquals(response is SimplePublicObject, true, "Response is not an instance of SimplePublicObject");
}

@test:Config {
    dependsOn: [testCreateMessage, testGetMessages, testGetMessageById, testUpdateMessage],
    groups: ["live_tests", "mock_tests"]
}
isolated function testDeleteMessage() returns error? {
    string testId = "";

    lock {
        testId = testCommunicationId;
    }

    http:Response response = check hecClient->/[testId].delete();

    test:assertEquals(response.statusCode == 204, true, "Failed to delete the message");
}

@test:Config {
    groups: ["live_test", "mock_tests"]
}
isolated function testCreateBatchOfMessages() returns error? {

    BatchResponseSimplePublicObject|error response = hecClient->/batch/create.post(
        payload = {
            inputs: [
                {
                    properties: {
                        "hs_communication_channel_type": "SMS",
                        "hs_communication_logged_from": "CRM",
                        "hs_communication_body": "Called Harry to discuss the contract.",
                        "hs_timestamp": "2022-11-12T15:48:22Z",
                        "hubspot_owner_id": testOwnerId
                    },
                    associations: [
                        {
                            types: [
                                {
                                    associationCategory: "HUBSPOT_DEFINED",
                                    associationTypeId: 81
                                }
                            ],
                            to: {
                                id: testAssociateId1
                            }
                        }
                    ]
                },
                {
                    properties: {
                        "hs_communication_channel_type": "WHATS_APP",
                        "hs_communication_logged_from": "CRM",
                        "hs_communication_body": "Sent an email to Harry to discuss the contract.",
                        "hs_timestamp": "2022-11-12T15:48:22Z",
                        "hubspot_owner_id": testOwnerId
                    },
                    associations: [
                        {
                            types: [
                                {
                                    associationCategory: "HUBSPOT_DEFINED",
                                    associationTypeId: 81
                                }
                            ],
                            to: {
                                id: testAssociateId2
                            }
                        }
                    ]
                },
                {
                    properties: {
                        "hs_communication_channel_type": "LINKEDIN_MESSAGE",
                        "hs_communication_logged_from": "CRM",
                        "hs_communication_body": "Sent an email to Harry to discuss the contract.",
                        "hs_timestamp": "2022-11-12T15:48:22Z",
                        "hubspot_owner_id": testOwnerId
                    },
                    associations: [
                        {
                            types: [
                                {
                                    associationCategory: "HUBSPOT_DEFINED",
                                    associationTypeId: 81
                                }
                            ],
                            to: {
                                id: testAssociateId1
                            }
                        },
                        {
                            types: [
                                {
                                    associationCategory: "HUBSPOT_DEFINED",
                                    associationTypeId: 81
                                }
                            ],
                            to: {
                                id: testAssociateId2
                            }
                        }
                    ]
                }
            ]
        }
    );

    if (response is BatchResponseSimplePublicObject) {
        string[] batchIds = response.results.map((result) => result.id);
        lock {
            testBatchIds = batchIds.clone();
        }
    }

    test:assertEquals(response is BatchResponseSimplePublicObject, true, "Response is not an instance of BatchResponseSimplePublicObject");
}

@test:Config {
    dependsOn: [testCreateBatchOfMessages],
    groups: ["live_test", "mock_tests"]
}
isolated function testRetrieveBatchOfMessages() returns error? {

    string[] testIds = [];

    lock {
        testIds = testBatchIds.clone();
    }

    BatchResponseSimplePublicObject response = check hecClient->/batch/read.post(
        payload = {
            properties: ["hs_timestamp", "hs_communication_channel_type"],
            propertiesWithHistory: ["hs_communication_body", "hs_createdate"],
            inputs: [
                {id: testIds[0]},
                {id: testIds[1]},
                {id: testIds[2]}
            ]
        }
    );

    test:assertTrue(response?.results.length() > 0, "Response is not an instance of BatchResponseSimplePublicObject");
};

@test:Config {
    dependsOn: [testCreateBatchOfMessages, testRetrieveBatchOfMessages],
    groups: ["live_test", "mock_tests"]
}
isolated function testUpdateBatchOfMessages() returns error? {
    string[] testIds = [];

    lock {
        testIds = testBatchIds.clone();
    }

    BatchResponseSimplePublicObject|error response = hecClient->/batch/update.post(
        payload = {
            inputs: [
                {
                    properties: {
                        "hs_communication_body": "Called Harry to discuss the contract."
                    },
                    id: testIds[0]
                },
                {
                    properties: {
                        "hs_communication_body": "Sent an email to Harry to discuss the contract."
                    },
                    id: testIds[1]
                },
                {
                    properties: {
                        "hs_communication_body": "Sent an email to Harry to discuss the contract."
                    },
                    id: testIds[2]
                }
            ]
        }
    );

    test:assertEquals(response is BatchResponseSimplePublicObject, true, "Response is not an instance of BatchResponseSimplePublicObject");
}

@test:Config {
    dependsOn: [testCreateBatchOfMessages, testRetrieveBatchOfMessages, testUpdateBatchOfMessages],
    groups: ["mock_tests"]
}
isolated function testArchiveBatchOfMessages() returns error? {
    string[] testIds = [];

    lock {
        testIds = testBatchIds.clone();
    }

    http:Response response = check hecClient->/batch/archive.post(
        payload = {
            inputs: [
                {id: testIds[0]},
                {id: testIds[1]},
                {id: testIds[2]}
            ]
        }
    );

    test:assertEquals(response.statusCode == 204, true, "Failed to delete the batch of messages");
}

@test:Config {
    dependsOn: [testCreateBatchOfMessages],
    groups: ["live_test", "mock_tests"]
}
isolated function testSearchMessage() returns error? {
    CollectionResponseWithTotalSimplePublicObjectForwardPaging|error response = check hecClient->/search.post(
        payload = {
            query: "contract"
        }
    );

    test:assertEquals(response is CollectionResponseWithTotalSimplePublicObjectForwardPaging, true, "Response is not an instance of CollectionResponseSimplePublicObject");
}
