[package]
org = "wso2"
name = "whatsapp_message"
version = "0.1.0"
distribution = "2201.11.0"

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.engagements.communications"
version = "2.0.0"
repository="local"

[build-options]
observabilityIncluded = true
