{
    "openapi": "3.0.1",
    "info": {
        "title": "Communications",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Your team frequently reaches out to your contacts via multiple channels that aren't directly connected to your HubSpot account, and you want to ensure all your communications to customers are centralized in one place.",
        "x-hubspot-related-documentation": [
            {
                "name": "Communications Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/engagements/communications"
            }
        ],
        "x-hubspot-introduction": "Use the communications API to associate messages from external channels (e.g., WhatsApp, LinkedIn, and SMS) to CRM records in your HubSpot account."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/communications"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Retrieve a batch of messages",
                "description": "Retrieve a batch of messages by ID (`communicationId`) or unique property value (`idProperty`). ",
                "operationId": "post-/crm/v3/objects/communications/batch/read_read",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            }
        },
        "/{communicationId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a message",
                "description": "Retrieve a message by its ID (`communicationId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
                "operationId": "get-/crm/v3/objects/communications/{communicationId}_getById",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a message",
                "description": "Delete a message by ID. You can restore deleted messages within 90 days of deletion. Learn more about [restoring activity records](https://knowledge.hubspot.com/records/restore-deleted-activity-in-a-record).",
                "operationId": "delete-/crm/v3/objects/communications/{communicationId}_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update a message",
                "description": "Update a message by ID (`communicationId`) or unique property value (`idProperty`). Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/communications/{communicationId}_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of messages",
                "description": "Delete a batch of messages by ID. A deleted message can be restored within 90 days of being deleted. Learn more about [restoring activity records](https://knowledge.hubspot.com/records/restore-deleted-activity-in-a-record).",
                "operationId": "post-/crm/v3/objects/communications/batch/archive_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of messages",
                "description": "Create a batch of messages. The `inputs` array can contain a `properties` object to define property values for each message, along with an `associations` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/communications/batch/create_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of messages",
                "description": "Update a batch of messages by ID (`communicationId`) or unique property value (`idProperty`). Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
                "operationId": "post-/crm/v3/objects/communications/batch/update_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve messages",
                "description": "Retrieve all messages, using query parameters to specify the information that gets returned.",
                "operationId": "get-/crm/v3/objects/communications_getPage",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a communication",
                "description": "Create a single message. Include a `properties` object to define [property values](https://developers.hubspot.com/docs/guides/api/crm/engagements/communications#properties), along with an `associations` array to define communication associations(https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/communications_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert a batch of messages",
                "description": "Create and update a batch of messages by a unique property. Messages that don't exist will be created, while existing messages will be updated.",
                "operationId": "post-/crm/v3/objects/communications/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "summary": "Search for messages",
                "description": "Search for messages by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
                "operationId": "post-/crm/v3/objects/communications/search_doSearch",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}